



spring:
    h2:
      console:
        enabled: true
    datasource:
      username: sa
      password:
      driver-class-name: org.h2.Driver
      hikari:
        jdbc-url: jdbc:h2:mem:testDB

      jpa:
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
        hibernate:
          ddl-auto: create-drop
      logging:
        level:
          org.springframework.security: trace


server:
  port: 8088
